### ISSUE TITLE
Binary Files + Requirements?

### ISSUE THREAD

**Issue by ashes999** [MatthijsKamstra/butterfly-example#1]
Hi,

Could you please check in the generated version of this site, possibly as a branch (gh-pages)? I want to know what it should look like.

I'm also not clear on what changes I need to make. Your site looks okay (when you hover over the page names, you get white on a white background, which is impossible to see).

I don't know what actual titles you want, and what actual requirements you have. Maybe you can update this to use Butterfly without any work-arounds (or without your changes) and point out what's broken and should be fixed.

With the current in-development v0.3, it looks fine to me. I must be missing something (other than page ordering, which is not obvious).

**Comment by MatthijsKamstra** [comment]
You want me to use my fork for this?

**Comment by MatthijsKamstra** [comment]
Done: http://matthijskamstra.github.io/butterfly-example/
Generated with my fork

**Comment by ashes999** [comment]
That's much better. For some reason, the website I see is drastically different than the one I generate with 0.3.

I'll do some diffs and see if I need to make any more changes.

**Comment by MatthijsKamstra** [comment]
I changed the titles a little because you didn't see what I meant by it, hope that doesn't interfere?

**Comment by ashes999** [comment]
That's cool. The current example is pretty clear. I'll ask here if I have any questions.

**Comment by ashes999** [comment]
\o/
